# Generated by Django 4.1.7 on 2023-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='editon',
            field=models.CharField(default='primera edicion', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(default='2000', max_length=4),
            preserve_default=False,
        ),
    ]
