# Generated by Django 4.1.7 on 2023-05-23 00:32

from django.db import migrations, models
import djbooks.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('djbooks', '0002_address_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='editon',
            new_name='edition',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='optional_img1',
            field=models.ImageField(blank=True, null=True, upload_to=djbooks.models.book_optional_img1_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='optional_img2',
            field=models.ImageField(blank=True, null=True, upload_to=djbooks.models.book_optional_img2_path),
        ),
    ]
