# Generated by Django 4.1.7 on 2023-06-12 23:03

from django.db import migrations, models
import django.db.models.deletion
import djbooks.helpers
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0004_book_related_books_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=functools.partial(djbooks.helpers.upload_extra_img, *(), **{'path': 'static/assets/books/'}))),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djbooks.book')),
            ],
        ),
    ]
