# Generated by Django 4.1.7 on 2023-06-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0005_extraimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='optional_img1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='optional_img2',
        ),
    ]
