# Generated by Django 4.1.7 on 2023-06-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0006_remove_book_optional_img1_remove_book_optional_img2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='paid',
        ),
    ]
