# Generated by Django 4.1.7 on 2023-06-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0008_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.CharField(choices=[('dhl', 'DHL'), ('sepomex', 'SEPOMEX'), ('local_pickup', 'Entrega directa')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PP', 'Paypal'), ('MP', 'Mercado Pago')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
